### ISSUE TITLE
No results shown in merge request

### ISSUE THREAD

**Issue by mschmieder** [Kyaak/danger-cobertura#13]
Hi @Kyaak 

I'm currently trying to use the plugin to show some coverage results created by `gcov` in combination with `gcovr` and show the results in GitLab on merge requests.

Unluckily the plugin seems not to report anything back. The file is there, I checked, and also the plugin does not complain about not being able to read it (which it does if the path is wrong...)

This is the dangerfile config
```ruby
cobertura.report = "code-analysis/coverage/gcov/coverage.xml"
cobertura.warn_if_file_less_than(percentage: 90.0)
cobertura.show_coverage
```

The output does not show anything

```bash
$ danger --fail-on-errors=true
Results:

Warnings:
- [ ] Please include a CHANGELOG entry.
```

I'm not sure if this has to do with the xml file itself though - that's why attached it to this issue.
[coverage.xml.zip](https://github.com/Kyaak/danger-cobertura/files/3702790/coverage.xml.zip)

Is there a way to easily test if the xml file if it works properly?

Best,
Matthias

P.S:
Greetings from Freiburg :)

**Comment by Kyaak** [comment]
Hey @mschmieder 
Thanks for using my plugin 👍 

Your xml file looks correct.  
Are your files modified? 

As noted in the Readme
`
It inspects only modified and added files, deleted ones are not considered useful for this report.
`

It's my intention to only focus on the merge request and not all files in the project.

P.S:
Greetins from Karlsruhe :)

**Comment by mschmieder** [comment]
@Kyaak 

That explains it! Sorry my bad...thanks for helping out!
